Repository Ven0maus/Emberpoint, pull requests merged in 2020-10, with the labels that each got.

#95 Issue #92: Player.cs has extraneous code
  Core/GameObjects/Entities/Player.cs
  Core/GameObjects/Map/EmberGrid.cs
  Core/UserInterface/Windows/FovWindow.cs
Labels: Improvement

#99 Refactored TileConfig in FovWindow
  Core/UserInterface/Windows/FovWindow.cs
Labels: Improvement

#100 Issue #30: EmberCell Effects
  Core/GameObjects/Abstracts/EmberEntity.cs
  Core/GameObjects/Entities/Player.cs
  Core/GameObjects/Interfaces/IEntity.cs
  Core/GameObjects/Interfaces/IEntityBaseStats.cs
  Core/GameObjects/Map/EmberCell.cs
  Tests/EmberCellEffectsTests.cs
  Tests/TestObjects/Entities/BaseEntity.cs
Labels: feature

#103 Issue #102: Use ProcessKeyboard with focus on Player entity to handle…
  Core/GameObjects/Abstracts/EmberEntity.cs
  Core/GameObjects/Entities/Player.cs
Labels: hacktoberfest-accepted

#104 Feature/issue81 ab
  Core/UserInterface/Windows/ContributorsWindow.cs
  Core/UserInterface/Windows/MainMenuWindow.cs
Labels: feature

#105 issue64-ab
  Core/Extensions/MonoGameExtensions.cs
  Core/GameObjects/Abstracts/Blueprint.cs
  Core/GameObjects/Blueprints/Config/BlueprintTiles.json
  Core/GameObjects/Map/EmberGrid.cs
  Core/UserInterface/Windows/FovWindow.cs
  Tests/FovWindowTests.cs
  Tests/TestObjects/Grids/BaseGrid.cs
  Tests/TestObjects/Windows/FovWindowMock.cs
Labels: Improvement

#106 Issue37-ab
  Core/GameObjects/Blueprints/Config/BlueprintTiles.json
Labels: Improvement
